import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex("products").del();

    // Inserts seed entries
    await knex("products").insert([
        { name: "Pizza Margherita", price: 45.90 },
        { name: "Pizza Calabresa", price: 49.90 },
        { name: "Pizza Portuguesa", price: 52.90 },
        { name: "Pizza Frango com Catupiry", price: 54.90 },
        { name: "Pizza Quatro Queijos", price: 56.90 },
        { name: "Pizza Pepperoni", price: 59.90 },
        { name: "Pizza Bacon", price: 51.90 },
        { name: "Pizza Napolitana", price: 48.90 },
        { name: "Pizza Vegetariana", price: 46.90 },
        { name: "Pizza Carne de Sol", price: 62.90 },

        { name: "Hambúrguer Artesanal", price: 32.90 },
        { name: "Hambúrguer Bacon", price: 36.90 },
        { name: "Hambúrguer Cheddar", price: 34.90 },
        { name: "Hambúrguer Duplo", price: 42.90 },
        { name: "X-Salada", price: 24.90 },
        { name: "X-Bacon", price: 28.90 },
        { name: "X-Frango", price: 26.90 },
        { name: "X-Tudo", price: 39.90 },
        { name: "Sanduíche Natural", price: 18.90 },
        { name: "Cachorro Quente Especial", price: 22.90 },

        { name: "Filé com Fritas", price: 58.90 },
        { name: "Filé ao Molho Madeira", price: 64.90 },
        { name: "Frango Grelhado", price: 39.90 },
        { name: "Frango à Parmegiana", price: 46.90 },
        { name: "Carne de Sol com Queijo", price: 62.90 },
        { name: "Bife Acebolado", price: 44.90 },
        { name: "Picanha na Chapa", price: 79.90 },
        { name: "Costela Suína", price: 68.90 },
        { name: "Peixe Frito", price: 55.90 },
        { name: "Camarão ao Alho e Óleo", price: 72.90 },

        { name: "Macarrão à Bolonhesa", price: 36.90 },
        { name: "Macarrão ao Molho Branco", price: 38.90 },
        { name: "Espaguete com Camarão", price: 59.90 },
        { name: "Lasanha de Queijo", price: 42.90 },
        { name: "Lasanha Bolonhesa", price: 44.90 },
        { name: "Nhoque ao Molho", price: 39.90 },
        { name: "Risoto de Frango", price: 45.90 },
        { name: "Risoto de Camarão", price: 65.90 },
        { name: "Arroz de Carne Seca", price: 49.90 },
        { name: "Strogonoff de Frango", price: 37.90 },

        { name: "Porção de Batata Frita", price: 18.90 },
        { name: "Batata Frita com Cheddar", price: 26.90 },
        { name: "Batata Frita com Bacon", price: 28.90 },
        { name: "Isca de Frango", price: 27.90 },
        { name: "Isca de Carne", price: 34.90 },
        { name: "Calabresa Acebolada", price: 29.90 },
        { name: "Queijo Coalho", price: 25.90 },
        { name: "Pastel de Carne", price: 8.90 },
        { name: "Pastel de Queijo", price: 8.90 },
        { name: "Coxinha", price: 7.50 },

        { name: "Refrigerante Coca-Cola Lata", price: 6.00 },
        { name: "Refrigerante Guaraná Lata", price: 6.00 },
        { name: "Refrigerante Coca-Cola 600ml", price: 8.00 },
        { name: "Refrigerante Guaraná 600ml", price: 8.00 },
        { name: "Suco Natural de Laranja", price: 8.50 },
        { name: "Suco Natural de Maracujá", price: 9.00 },
        { name: "Suco Natural de Morango", price: 10.00 },
        { name: "Água Mineral", price: 4.00 },
        { name: "Água com Gás", price: 5.00 },
        { name: "Café Expresso", price: 5.50 },

        { name: "Cappuccino", price: 9.90 },
        { name: "Chocolate Quente", price: 12.90 },
        { name: "Milk Shake Chocolate", price: 16.90 },
        { name: "Milk Shake Morango", price: 16.90 },
        { name: "Milk Shake Ovomaltine", price: 18.90 },
        { name: "Vitamina de Banana", price: 11.90 },
        { name: "Vitamina de Morango", price: 12.90 },
        { name: "Açaí Pequeno", price: 14.90 },
        { name: "Açaí Médio", price: 19.90 },
        { name: "Açaí Grande", price: 24.90 },

        { name: "Pudim de Leite", price: 12.90 },
        { name: "Brownie com Sorvete", price: 18.90 },
        { name: "Petit Gateau", price: 22.90 },
        { name: "Torta de Chocolate", price: 15.90 },
        { name: "Torta de Limão", price: 14.90 },
        { name: "Cheesecake", price: 19.90 },
        { name: "Sorvete de Chocolate", price: 10.90 },
        { name: "Sorvete de Morango", price: 10.90 },
        { name: "Sorvete de Baunilha", price: 10.90 },
        { name: "Salada de Frutas", price: 13.90 },

        { name: "Combo Hambúrguer e Batata", price: 45.90 },
        { name: "Combo Pizza e Refrigerante", price: 62.90 },
        { name: "Combo Família", price: 99.90 },
        { name: "Combo Casal", price: 79.90 },
        { name: "Prato Executivo Frango", price: 29.90 },
        { name: "Prato Executivo Carne", price: 34.90 },
        { name: "Prato Executivo Peixe", price: 39.90 },
        { name: "Marmita Pequena", price: 18.90 },
        { name: "Marmita Grande", price: 24.90 },
        { name: "Feijoada Completa", price: 49.90 },

        { name: "Caldo de Feijão", price: 14.90 },
        { name: "Caldo de Frango", price: 14.90 },
        { name: "Sopa de Legumes", price: 16.90 },
        { name: "Salada Caesar", price: 22.90 },
        { name: "Salada Tropical", price: 24.90 },
        { name: "Pão de Alho", price: 9.90 },
        { name: "Tábua de Frios", price: 59.90 },
        { name: "Bruschetta", price: 21.90 },
        { name: "Omelete Especial", price: 26.90 },
        { name: "Crepioca", price: 17.90 }
    ]);
};
